package com.mobiera.aircast.api.v1.preference;

public enum GetPreferenceRequestResult {
	
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, 
	ERROR_MISSING_PREFERENCE_NAME, 
	ERROR_MISSING_PREFERENCE_TYPE, 
	ERROR_INVALID_NAME_FOR_PREFERENCE_TYPE,

}
