// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: ValueObject.vsl in andromda-java-cartridge.
//
package com.mobiera.aircast.commons.vo;


import java.time.Instant;

import com.mobiera.commons.vo.CommonVO;


/**
 * 
 */
public class MtSpoolVO
    implements CommonVO
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 641387377243738960L;

    public MtSpoolVO()
    {
    }

    public MtSpoolVO(java.lang.Long id, Instant spooledTs, java.lang.Integer tries, Instant nextTry, java.lang.Boolean sent, java.lang.Boolean dlred, java.lang.Boolean dlrRequested, java.lang.String msisdn)
    {
        this.id = id;
        this.spooledTs = spooledTs;
        this.tries = tries;
        this.nextTry = nextTry;
        this.sent = sent;
        this.dlred = dlred;
        this.dlrRequested = dlrRequested;
        this.msisdn = msisdn;
    }

    /**
     * Copies constructor from other MtSpoolVO
     *
     * @param otherBean, cannot be <code>null</code>
     * @throws java.lang.NullPointerException if the argument is <code>null</code>
     */
    public MtSpoolVO(MtSpoolVO otherBean)
    {
        this(otherBean.getId(), otherBean.getSpooledTs(), otherBean.getTries(), otherBean.getNextTry(), otherBean.getSent(), otherBean.getDlred(), otherBean.getDlrRequested(), otherBean.getMsisdn());
    }

    /**
     * Copies all properties from the argument value object into this value object.
     */
    public void copy(MtSpoolVO otherBean)
    {
        if (otherBean != null)
        {
            this.setId(otherBean.getId());
            this.setSpooledTs(otherBean.getSpooledTs());
            this.setTries(otherBean.getTries());
            this.setNextTry(otherBean.getNextTry());
            this.setSent(otherBean.getSent());
            this.setDlred(otherBean.getDlred());
            this.setDlrRequested(otherBean.getDlrRequested());
            this.setMsisdn(otherBean.getMsisdn());
        }
    }

    private java.lang.Long id;

    /**
     * 
     */
    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    private Instant spooledTs;

    /**
     * 
     */
    public Instant getSpooledTs()
    {
        return this.spooledTs;
    }

    public void setSpooledTs(Instant spooledTs)
    {
        this.spooledTs = spooledTs;
    }

    private java.lang.Integer tries;

    /**
     * 
     */
    public java.lang.Integer getTries()
    {
        return this.tries;
    }

    public void setTries(java.lang.Integer tries)
    {
        this.tries = tries;
    }

    private Instant nextTry;

    /**
     * 
     */
    public Instant getNextTry()
    {
        return this.nextTry;
    }

    public void setNextTry(Instant nextTry)
    {
        this.nextTry = nextTry;
    }

    private java.lang.Boolean sent;

    /**
     * 
     */
    public java.lang.Boolean getSent()
    {
        return this.sent;
    }

    public void setSent(java.lang.Boolean sent)
    {
        this.sent = sent;
    }

    private java.lang.Boolean dlred;

    /**
     * 
     */
    public java.lang.Boolean getDlred()
    {
        return this.dlred;
    }

    public void setDlred(java.lang.Boolean dlred)
    {
        this.dlred = dlred;
    }

    private java.lang.Boolean dlrRequested;

    /**
     * 
     */
    public java.lang.Boolean getDlrRequested()
    {
        return this.dlrRequested;
    }

    public void setDlrRequested(java.lang.Boolean dlrRequested)
    {
        this.dlrRequested = dlrRequested;
    }

    private java.lang.String msisdn;

    /**
     * 
     */
    public java.lang.String getMsisdn()
    {
        return this.msisdn;
    }

    public void setMsisdn(java.lang.String msisdn)
    {
        this.msisdn = msisdn;
    }

}