package com.mobiera.aircast.api.v1.applet;

public enum SaveAppletRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_INVALID_URL,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_BAD_ARGUMENT, ERROR_NULL_ARGUMENT
}
