package com.mobiera.aircast.api.v1.sim_profile;

public enum SaveSimProfileRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_IMSI_RANGE_OVERLAP,
	ERROR_ICCID_RANGE_OVERLAP,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_BAD_ARGUMENT, ERROR_NULL_ARGUMENT,
}
