package com.mobiera.aircast.api.v1.sleepy.command;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.mobiera.aircast.api.v1.sleepy.action.Action;
import com.mobiera.aircast.api.v1.sleepy.action.Variable;
import com.mobiera.commons.introspection.Required;
import com.mobiera.commons.introspection.Validator;

/**
 * Represent a Push Flow that will be sent to Mobile Entity.
 * <p>
 * <b>actions</b>: a list of {@link Action} TLVs, executed sequentially (starting by the first one), in an order that depends on user/phone behavior.
 * <p>
 * <b>outputVariable</b>: a {@link Variable} used to receive information input by the User or generated by SendOptinOffer flow;
 * <p>
 * <b>variables</b>: a list of {@link Variable} (Variable declaration). All needed variables in the flow must be declared here, including outputVariable.
 * <p>
 * @author mj
 */
@JsonInclude(Include.NON_NULL)
public class SendOptinOfferCommand extends ApiSleepyCommand implements Serializable {

	private static final long serialVersionUID = -8831323578236289994L;
	@Required
	@Validator(minSize=1)
	private List<Action> actions;
	private Variable outputVariable;
	private List<Variable> variables;
	public List<Action> getActions() {
		return actions;
	}
	public void setActions(List<Action> actions) {
		this.actions = actions;
	}
	public Variable getOutputVariable() {
		return outputVariable;
	}
	public void setOutputVariable(Variable outputVariable) {
		this.outputVariable = outputVariable;
	}
	public List<Variable> getVariables() {
		return variables;
	}
	public void setVariables(List<Variable> variables) {
		this.variables = variables;
	}
	
	
}
