package com.mobiera.aircast.api.v3.role;

public enum SaveRoleRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_INVALID_URL,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_NULL_ARGUMENT, ERROR_BAD_ARGUMENT,
}
