package com.mobiera.aircast.api.v1.sim;

public enum CreateOrUpdateSimRequestResult {
	OK,
	ERROR_INVALID_MSISDN,
	ERROR_MSISDN_ALREADY_IN_USE,
	ERROR_MSISDN_INVALID_VALID_UNTIL_DATE,
	ERROR_DATA_LENGTH_NOT_SUPPORTED,
	ERROR_TARGET_NOT_PROVISIONED,
	ERROR_INVALID_IMSI,
	ERROR_INVALID_ICCID,
	ERROR_INVALID_IMEI,
	ERROR_INVALID_SIM_PROFILE_ID,
	ERROR_NO_TARGET,
	ERROR_DATA_INTEGRITY,
	ERROR_CIPHERING,
	ERROR_PERMISSION_DENIED,
	ERROR_JSON_PROCESSING,
	ERROR_UNKNOWN,
}
