package com.mobiera.aircast.api.v1.sim;

public enum SetSimMsisdnRequestResult {
	OK,
	ERROR_INVALID_MSISDN,
	ERROR_DATA_INTEGRITY,
	ERROR_MSISDN_ALREADY_IN_USE,
	ERROR_MSISDN_INVALID_VALIDITY_DATE,
	ERROR_DATA_LENGTH_NOT_SUPPORTED,
	ERROR_TARGET_NOT_PROVISIONED,
	ERROR_NO_TARGET,
	ERROR_PERMISSION_DENIED,
	ERROR_JSON_PROCESSING,
	ERROR_UNKNOWN, 
}
