package com.mobiera.aircast.api.v1.sleepy;

public enum SleepyPushResponseResult {
	DELIVERED,
	UNDELIVERED,
	OK, 
	ERROR_CMD_NOT_SUPPORTED, 
	ERROR_WRONG_SESSION_ID, 
	ERROR_WRONG_PROTOCOL_VER, 
	ERROR_CMD_FAILED, 
	ERROR_WRONG_RSP_PARAMS, 
	ERROR_UNSPECIFIED, 
	ERROR_RSP_FAILED, 
	ERROR_CMD_ABORTED, 
	ERROR_CIPHERING_ERROR
}
