package com.mobiera.aircast.api.v1.tp_rule;

public enum SaveTpRuleRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_UNSUPPORTED, ERROR_BAD_ARGUMENT, ERROR_NULL_ARGUMENT,
}
