package com.mobiera.aircast.api.v1.campaign;

public enum RefuseCampaignRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_INVALID_ENTITY,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_NULL_ARGUMENT, ERROR_BAD_ARGUMENT,
	ERROR_DATA_INTEGRITY, ERROR_SERVICE_NOT_AVAILABLE
}
