package com.mobiera.aircast.api.v1.campaign;

public enum RunCampaignRequestResult {
	OK,
	ERROR_PERMISSION_DENIED,
	ERROR_NO_TARGET,
	ERROR_MISSING_REQUEST_ID,
	ERROR_MISSING_CAMPAIGN,
	ERROR_DEAD_SIM,
	ERROR_DISABLED_ENTITY,
	ERROR_TARGET_NOT_PROVISIONED,
	ERROR_TARGET_NOT_COMPATIBLE,
	ERROR_INVALID_CAMPAIGN,
	ERROR_INVALID_CAMPAIGN_TYPE,
	ERROR_DUPLICATED_REQUEST_ID,
	ERROR_DATA_INTEGRITY,
	ERROR_NULL_ENTITY,
	ERROR_INVALID_RUN_STATUS,
	ERROR_UNKNOWN,
	ERROR_QUEUE_FULL
	}
