package com.mobiera.aircast.api.v1.file;

public enum FileUploadRequestResult {
	OK,
	ERROR_MISSING_ENTITY,
	ERROR_PERMISSION_DENIED,
	ERROR_UNKNOWN, ERROR_NULL_ARGUMENT, ERROR_MISSING_ARGUMENT, IO_EXCEPTION
}
